name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout github repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtcreator qtbase5-dev qt5-qmake doxygen cmake graphviz texlive ninja-build make

      - name: Configure and Build CMake
        run: |
          cmake -GNinja -S ${{github.workspace}} -B ${{github.workspace}}/build
          cmake --build ${{github.workspace}}/build --target pathfinding

      #- name: Test
      #  working-directory: ${{.github.workspace}}/build
      #  run: ctest -C ${{env.BUILD_TYPE}}

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: build/pathfinding
          compression-level: 0

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: build/docs/latex/refman.pdf
          compression-level: 0

