name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout and install dependencies
      - uses: actions/checkout@v3
        run: |
          sudo apt-get update
          sudo apt-get install -y qtcreator qtbase5-dev qt5-qmake graphviz graphicx texlive

      - name: Configure and Build CMake
        run: cmake -Bbuild ${{.github.workspace}}/build --target pathfinding -j 14

      #- name: Test
      #  working-directory: ${{.github.workspace}}/build
      #  run: ctest -C ${{env.BUILD_TYPE}}

      - name: Upload binary
      - uses: actions/upload-artifact@v3
        with:
          name: binary
          path: build/pathfinding
          compression-level: 0

      - name: Upload documentation
      - uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: build/docs/latex/refman.pdf
          compression-level: 0

